---
title: "Index"
date: "`r Sys.Date()`"
author:
  - name: Arun Seetharam
    affiliation: Tuteja Lab
    affiliation_url: https://www.tutejalab.org
output:
  #pdf_document: default
  rmdformats::readthedown:
    self_contained: true
    thumbnails: false
    lightbox: true
    gallery: true
    highlight: tango
---

```{r setup, include=FALSE}
options(max.print = "125")
knitr::opts_chunk$set(
  echo = TRUE,
  collapse = TRUE,
  comment = "#>",
  fig.path = "assets/",
  fig.width = 8,
  prompt = FALSE,
  tidy = FALSE,
  message = FALSE,
  warning = TRUE
)
knitr::opts_knit$set(width = 75)
```

# Mouse Trophoblast smallRNAseq analyses

Performed  at [Tuteja Lab](https://www.tutejalab.org), Iowa State University, Ames IA-50011

### Documentation

The Wiki for the entire analyses is provided in this R-markdown files [`1_smallRNAseq.Rmd`](1_smallRNAseq.Rmd) and [`2_proteomics.Rmd`](2_proteomics.Rmd). The rendered html file is accessible on this link:

1. [Small RNAseq analyses](https://tuteja-lab.github.io/mouse.trophoblast.smallRNAseq/1_smallRNAseq.html)
2. [Proteomics analyses](https://tuteja-lab.github.io/mouse.trophoblast.smallRNAseq/2_proteomics.html)

### Data availability

* Small RNAseq data available for download upon publication from NCBI GEO [GSE222855](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE222855)
* Proteomics data available for download upon pulication from [Massive UCSD repository](http://massive.ucsd.edu/ProteoSAFe/status.jsp?task=35b93125f20f40ebbae166e5f8657860)

### Contacts

1. Project related questions: Geetu Tuteja
2. Scripts and workflow related questions: please open an [issue](https://github.com/Tuteja-Lab/mouse.trophoblast.smallRNAseq/issues/new) here on GitHub.


### Publication

If you use the scripts from this repository in your research, please cite this publication:

_coming soon_

Kinkade, J. A., Seetharam, A. S., Sachdev, S., Bivens, N. J., Phinney, B. S., Grigorean, G., Roberts, R. M., Tuteja, G., Rosenfeld, C. S., Extracellular Vesicle Contents of Mouse Trophoblast Cells and Their Predicted Influence on Fetal Brain Development _(in preparation)_


